name: Hashiba
favicon: null
layout_spectrum: 0.75315
typography_spectrum: 0.035288762766867876
title: Hashiba
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d3d3'
    - '#a3a3a3'
    - '#7f7f7f'
    - '#525252'
    - '#333333'
  brandStrength: 0.875
  lightness: 0.4980762319173664
  saturation: 0.30624333629384637
  rhythmicContrast: 0.75
purpose: []
